// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package forum

import (
	"server/api/forum"
)

type ControllerV1 struct{}

func NewV1() forum.IForumV1 {
	return &ControllerV1{}
}
