// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package iam

import (
	"server/api/iam"
)

type ControllerV1 struct{}

func NewV1() iam.IIamV1 {
	return &ControllerV1{}
}
