// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package economy

import (
	"server/api/economy"
)

type ControllerV1 struct{}

func NewV1() economy.IEconomyV1 {
	return &ControllerV1{}
}
