// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package tracker

import (
	"server/api/tracker"
)

type ControllerV1 struct{}

func NewV1() tracker.ITrackerV1 {
	return &ControllerV1{}
}
