// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// catalogRequestDao is the data access object for the table catalog_request.
// You can define custom methods on it to extend its functionality as needed.
type catalogRequestDao struct {
	*internal.CatalogRequestDao
}

var (
	// CatalogRequest is a globally accessible object for table catalog_request operations.
	CatalogRequest = catalogRequestDao{internal.NewCatalogRequestDao()}
)

// Add your custom methods and functionality below.
