// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// catalogTagDao is the data access object for the table catalog_tag.
// You can define custom methods on it to extend its functionality as needed.
type catalogTagDao struct {
	*internal.CatalogTagDao
}

var (
	// CatalogTag is a globally accessible object for table catalog_tag operations.
	CatalogTag = catalogTagDao{internal.NewCatalogTagDao()}
)

// Add your custom methods and functionality below.
