// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// catalogTorrentTagDao is the data access object for the table catalog_torrent_tag.
// You can define custom methods on it to extend its functionality as needed.
type catalogTorrentTagDao struct {
	*internal.CatalogTorrentTagDao
}

var (
	// CatalogTorrentTag is a globally accessible object for table catalog_torrent_tag operations.
	CatalogTorrentTag = catalogTorrentTagDao{internal.NewCatalogTorrentTagDao()}
)

// Add your custom methods and functionality below.
