// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// catalogTorrentRewardDao is the data access object for the table catalog_torrent_reward.
// You can define custom methods on it to extend its functionality as needed.
type catalogTorrentRewardDao struct {
	*internal.CatalogTorrentRewardDao
}

var (
	// CatalogTorrentReward is a globally accessible object for table catalog_torrent_reward operations.
	CatalogTorrentReward = catalogTorrentRewardDao{internal.NewCatalogTorrentRewardDao()}
)

// Add your custom methods and functionality below.
