// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// catalogTorrentMetaDao is the data access object for the table catalog_torrent_meta.
// You can define custom methods on it to extend its functionality as needed.
type catalogTorrentMetaDao struct {
	*internal.CatalogTorrentMetaDao
}

var (
	// CatalogTorrentMeta is a globally accessible object for table catalog_torrent_meta operations.
	CatalogTorrentMeta = catalogTorrentMetaDao{internal.NewCatalogTorrentMetaDao()}
)

// Add your custom methods and functionality below.
