// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// catalogCommentDao is the data access object for the table catalog_comment.
// You can define custom methods on it to extend its functionality as needed.
type catalogCommentDao struct {
	*internal.CatalogCommentDao
}

var (
	// CatalogComment is a globally accessible object for table catalog_comment operations.
	CatalogComment = catalogCommentDao{internal.NewCatalogCommentDao()}
)

// Add your custom methods and functionality below.
