// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// catalogCommentLikeDao is the data access object for the table catalog_comment_like.
// You can define custom methods on it to extend its functionality as needed.
type catalogCommentLikeDao struct {
	*internal.CatalogCommentLikeDao
}

var (
	// CatalogCommentLike is a globally accessible object for table catalog_comment_like operations.
	CatalogCommentLike = catalogCommentLikeDao{internal.NewCatalogCommentLikeDao()}
)

// Add your custom methods and functionality below.
