// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// catalogTorrentLikeDao is the data access object for the table catalog_torrent_like.
// You can define custom methods on it to extend its functionality as needed.
type catalogTorrentLikeDao struct {
	*internal.CatalogTorrentLikeDao
}

var (
	// CatalogTorrentLike is a globally accessible object for table catalog_torrent_like operations.
	CatalogTorrentLike = catalogTorrentLikeDao{internal.NewCatalogTorrentLikeDao()}
)

// Add your custom methods and functionality below.
