// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// catalogTorrentBookmarkDao is the data access object for the table catalog_torrent_bookmark.
// You can define custom methods on it to extend its functionality as needed.
type catalogTorrentBookmarkDao struct {
	*internal.CatalogTorrentBookmarkDao
}

var (
	// CatalogTorrentBookmark is a globally accessible object for table catalog_torrent_bookmark operations.
	CatalogTorrentBookmark = catalogTorrentBookmarkDao{internal.NewCatalogTorrentBookmarkDao()}
)

// Add your custom methods and functionality below.
