// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// catalogCommentRewardDao is the data access object for the table catalog_comment_reward.
// You can define custom methods on it to extend its functionality as needed.
type catalogCommentRewardDao struct {
	*internal.CatalogCommentRewardDao
}

var (
	// CatalogCommentReward is a globally accessible object for table catalog_comment_reward operations.
	CatalogCommentReward = catalogCommentRewardDao{internal.NewCatalogCommentRewardDao()}
)

// Add your custom methods and functionality below.
