// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// catalogTorrentFileDao is the data access object for the table catalog_torrent_file.
// You can define custom methods on it to extend its functionality as needed.
type catalogTorrentFileDao struct {
	*internal.CatalogTorrentFileDao
}

var (
	// CatalogTorrentFile is a globally accessible object for table catalog_torrent_file operations.
	CatalogTorrentFile = catalogTorrentFileDao{internal.NewCatalogTorrentFileDao()}
)

// Add your custom methods and functionality below.
