// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// catalogSubtitleDao is the data access object for the table catalog_subtitle.
// You can define custom methods on it to extend its functionality as needed.
type catalogSubtitleDao struct {
	*internal.CatalogSubtitleDao
}

var (
	// CatalogSubtitle is a globally accessible object for table catalog_subtitle operations.
	CatalogSubtitle = catalogSubtitleDao{internal.NewCatalogSubtitleDao()}
)

// Add your custom methods and functionality below.
