// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// catalogTagGroupDao is the data access object for the table catalog_tag_group.
// You can define custom methods on it to extend its functionality as needed.
type catalogTagGroupDao struct {
	*internal.CatalogTagGroupDao
}

var (
	// CatalogTagGroup is a globally accessible object for table catalog_tag_group operations.
	CatalogTagGroup = catalogTagGroupDao{internal.NewCatalogTagGroupDao()}
)

// Add your custom methods and functionality below.
