// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// catalogTorrentDao is the data access object for the table catalog_torrent.
// You can define custom methods on it to extend its functionality as needed.
type catalogTorrentDao struct {
	*internal.CatalogTorrentDao
}

var (
	// CatalogTorrent is a globally accessible object for table catalog_torrent operations.
	CatalogTorrent = catalogTorrentDao{internal.NewCatalogTorrentDao()}
)

// Add your custom methods and functionality below.
