// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// economyRewardRecordDao is the data access object for the table economy_reward_record.
// You can define custom methods on it to extend its functionality as needed.
type economyRewardRecordDao struct {
	*internal.EconomyRewardRecordDao
}

var (
	// EconomyRewardRecord is a globally accessible object for table economy_reward_record operations.
	EconomyRewardRecord = economyRewardRecordDao{internal.NewEconomyRewardRecordDao()}
)

// Add your custom methods and functionality below.
