// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import "server/internal/dao/internal"

type economyShopOrderDao struct {
	*internal.EconomyShopOrderDao
}

var EconomyShopOrder = economyShopOrderDao{internal.NewEconomyShopOrderDao()}
