// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// economyBonusLogDao is the data access object for the table economy_bonus_log.
// You can define custom methods on it to extend its functionality as needed.
type economyBonusLogDao struct {
	*internal.EconomyBonusLogDao
}

var (
	// EconomyBonusLog is a globally accessible object for table economy_bonus_log operations.
	EconomyBonusLog = economyBonusLogDao{internal.NewEconomyBonusLogDao()}
)

// Add your custom methods and functionality below.
