// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// forumTopicLikeDao is the data access object for the table forum_topic_like.
// You can define custom methods on it to extend its functionality as needed.
type forumTopicLikeDao struct {
	*internal.ForumTopicLikeDao
}

var (
	// ForumTopicLike is a globally accessible object for table forum_topic_like operations.
	ForumTopicLike = forumTopicLikeDao{internal.NewForumTopicLikeDao()}
)

// Add your custom methods and functionality below.
