// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// forumNodeDao is the data access object for the table forum_node.
// You can define custom methods on it to extend its functionality as needed.
type forumNodeDao struct {
	*internal.ForumNodeDao
}

var (
	// ForumNode is a globally accessible object for table forum_node operations.
	ForumNode = forumNodeDao{internal.NewForumNodeDao()}
)

// Add your custom methods and functionality below.
