// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// forumTopicDao is the data access object for the table forum_topic.
// You can define custom methods on it to extend its functionality as needed.
type forumTopicDao struct {
	*internal.ForumTopicDao
}

var (
	// ForumTopic is a globally accessible object for table forum_topic operations.
	ForumTopic = forumTopicDao{internal.NewForumTopicDao()}
)

// Add your custom methods and functionality below.
