// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// forumTopicBookmarkDao is the data access object for the table forum_topic_bookmark.
// You can define custom methods on it to extend its functionality as needed.
type forumTopicBookmarkDao struct {
	*internal.ForumTopicBookmarkDao
}

var (
	// ForumTopicBookmark is a globally accessible object for table forum_topic_bookmark operations.
	ForumTopicBookmark = forumTopicBookmarkDao{internal.NewForumTopicBookmarkDao()}
)

// Add your custom methods and functionality below.
