// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// forumReplyLikeDao is the data access object for the table forum_reply_like.
// You can define custom methods on it to extend its functionality as needed.
type forumReplyLikeDao struct {
	*internal.ForumReplyLikeDao
}

var (
	// ForumReplyLike is a globally accessible object for table forum_reply_like operations.
	ForumReplyLike = forumReplyLikeDao{internal.NewForumReplyLikeDao()}
)

// Add your custom methods and functionality below.
