// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// forumCategoryDao is the data access object for the table forum_category.
// You can define custom methods on it to extend its functionality as needed.
type forumCategoryDao struct {
	*internal.ForumCategoryDao
}

var (
	// ForumCategory is a globally accessible object for table forum_category operations.
	ForumCategory = forumCategoryDao{internal.NewForumCategoryDao()}
)

// Add your custom methods and functionality below.
