// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// iamUserDao is the data access object for the table iam_user.
// You can define custom methods on it to extend its functionality as needed.
type iamUserDao struct {
	*internal.IamUserDao
}

var (
	// IamUser is a globally accessible object for table iam_user operations.
	IamUser = iamUserDao{internal.NewIamUserDao()}
)

// Add your custom methods and functionality below.
