// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// iamUserPeriodStatDao is the data access object for the table iam_user_period_stat.
// You can define custom methods on it to extend its functionality as needed.
type iamUserPeriodStatDao struct {
	*internal.IamUserPeriodStatDao
}

var (
	// IamUserPeriodStat is a globally accessible object for table iam_user_period_stat operations.
	IamUserPeriodStat = iamUserPeriodStatDao{internal.NewIamUserPeriodStatDao()}
)

// Add your custom methods and functionality below.
