// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// iamUserStatDao is the data access object for the table iam_user_stat.
// You can define custom methods on it to extend its functionality as needed.
type iamUserStatDao struct {
	*internal.IamUserStatDao
}

var (
	// IamUserStat is a globally accessible object for table iam_user_stat operations.
	IamUserStat = iamUserStatDao{internal.NewIamUserStatDao()}
)

// Add your custom methods and functionality below.
