// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// iamUserProfileDao is the data access object for the table iam_user_profile.
// You can define custom methods on it to extend its functionality as needed.
type iamUserProfileDao struct {
	*internal.IamUserProfileDao
}

var (
	// IamUserProfile is a globally accessible object for table iam_user_profile operations.
	IamUserProfile = iamUserProfileDao{internal.NewIamUserProfileDao()}
)

// Add your custom methods and functionality below.
