// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// iamUserRecoveryCodeDao is the data access object for the table iam_user_recovery_code.
// You can define custom methods on it to extend its functionality as needed.
type iamUserRecoveryCodeDao struct {
	*internal.IamUserRecoveryCodeDao
}

var (
	// IamUserRecoveryCode is a globally accessible object for table iam_user_recovery_code operations.
	IamUserRecoveryCode = iamUserRecoveryCodeDao{internal.NewIamUserRecoveryCodeDao()}
)

// Add your custom methods and functionality below.
