// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// iamRoleDao is the data access object for the table iam_role.
// You can define custom methods on it to extend its functionality as needed.
type iamRoleDao struct {
	*internal.IamRoleDao
}

var (
	// IamRole is a globally accessible object for table iam_role operations.
	IamRole = iamRoleDao{internal.NewIamRoleDao()}
)

// Add your custom methods and functionality below.
