// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// iamUserSettingDao is the data access object for the table iam_user_setting.
// You can define custom methods on it to extend its functionality as needed.
type iamUserSettingDao struct {
	*internal.IamUserSettingDao
}

var (
	// IamUserSetting is a globally accessible object for table iam_user_setting operations.
	IamUserSetting = iamUserSettingDao{internal.NewIamUserSettingDao()}
)

// Add your custom methods and functionality below.
