// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// iamInviteDao is the data access object for the table iam_invite.
// You can define custom methods on it to extend its functionality as needed.
type iamInviteDao struct {
	*internal.IamInviteDao
}

var (
	// IamInvite is a globally accessible object for table iam_invite operations.
	IamInvite = iamInviteDao{internal.NewIamInviteDao()}
)

// Add your custom methods and functionality below.
