// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// iamUserMonthlyStatDao is the data access object for the table iam_user_monthly_stat.
// You can define custom methods on it to extend its functionality as needed.
type iamUserMonthlyStatDao struct {
	*internal.IamUserMonthlyStatDao
}

var (
	// IamUserMonthlyStat is a globally accessible object for table iam_user_monthly_stat operations.
	IamUserMonthlyStat = iamUserMonthlyStatDao{internal.NewIamUserMonthlyStatDao()}
)

// Add your custom methods and functionality below.
