// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// iamUserPermissionDao is the data access object for the table iam_user_permission.
// You can define custom methods on it to extend its functionality as needed.
type iamUserPermissionDao struct {
	*internal.IamUserPermissionDao
}

var (
	// IamUserPermission is a globally accessible object for table iam_user_permission operations.
	IamUserPermission = iamUserPermissionDao{internal.NewIamUserPermissionDao()}
)

// Add your custom methods and functionality below.
