// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// iamUserDailyStatDao is the data access object for the table iam_user_daily_stat.
// You can define custom methods on it to extend its functionality as needed.
type iamUserDailyStatDao struct {
	*internal.IamUserDailyStatDao
}

var (
	// IamUserDailyStat is a globally accessible object for table iam_user_daily_stat operations.
	IamUserDailyStat = iamUserDailyStatDao{internal.NewIamUserDailyStatDao()}
)

// Add your custom methods and functionality below.
