// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// modCheaterLogDao is the data access object for the table mod_cheater_log.
// You can define custom methods on it to extend its functionality as needed.
type modCheaterLogDao struct {
	*internal.ModCheaterLogDao
}

var (
	// ModCheaterLog is a globally accessible object for table mod_cheater_log operations.
	ModCheaterLog = modCheaterLogDao{internal.NewModCheaterLogDao()}
)

// Add your custom methods and functionality below.
