// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// modUserLogDao is the data access object for the table mod_user_log.
// You can define custom methods on it to extend its functionality as needed.
type modUserLogDao struct {
	*internal.ModUserLogDao
}

var (
	// ModUserLog is a globally accessible object for table mod_user_log operations.
	ModUserLog = modUserLogDao{internal.NewModUserLogDao()}
)

// Add your custom methods and functionality below.
