// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// modIpBanDao is the data access object for the table mod_ip_ban.
// You can define custom methods on it to extend its functionality as needed.
type modIpBanDao struct {
	*internal.ModIpBanDao
}

var (
	// ModIpBan is a globally accessible object for table mod_ip_ban operations.
	ModIpBan = modIpBanDao{internal.NewModIpBanDao()}
)

// Add your custom methods and functionality below.
