// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// modStaffMessageDao is the data access object for the table mod_staff_message.
// You can define custom methods on it to extend its functionality as needed.
type modStaffMessageDao struct {
	*internal.ModStaffMessageDao
}

var (
	// ModStaffMessage is a globally accessible object for table mod_staff_message operations.
	ModStaffMessage = modStaffMessageDao{internal.NewModStaffMessageDao()}
)

// Add your custom methods and functionality below.
