// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// modReportDao is the data access object for the table mod_report.
// You can define custom methods on it to extend its functionality as needed.
type modReportDao struct {
	*internal.ModReportDao
}

var (
	// ModReport is a globally accessible object for table mod_report operations.
	ModReport = modReportDao{internal.NewModReportDao()}
)

// Add your custom methods and functionality below.
