// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// siteUserTaskDao is the data access object for the table site_user_task.
// You can define custom methods on it to extend its functionality as needed.
type siteUserTaskDao struct {
	*internal.SiteUserTaskDao
}

var (
	// SiteUserTask is a globally accessible object for table site_user_task operations.
	SiteUserTask = siteUserTaskDao{internal.NewSiteUserTaskDao()}
)

// Add your custom methods and functionality below.
