// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// siteChatMessageDao is the data access object for the table site_chat_message.
// You can define custom methods on it to extend its functionality as needed.
type siteChatMessageDao struct {
	*internal.SiteChatMessageDao
}

var (
	// SiteChatMessage is a globally accessible object for table site_chat_message operations.
	SiteChatMessage = siteChatMessageDao{internal.NewSiteChatMessageDao()}
)

// Add your custom methods and functionality below.
