// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// siteAnnouncementDao is the data access object for the table site_announcement.
// You can define custom methods on it to extend its functionality as needed.
type siteAnnouncementDao struct {
	*internal.SiteAnnouncementDao
}

var (
	// SiteAnnouncement is a globally accessible object for table site_announcement operations.
	SiteAnnouncement = siteAnnouncementDao{internal.NewSiteAnnouncementDao()}
)

// Add your custom methods and functionality below.
