// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// siteAnnouncementReadDao is the data access object for the table site_announcement_read.
// You can define custom methods on it to extend its functionality as needed.
type siteAnnouncementReadDao struct {
	*internal.SiteAnnouncementReadDao
}

var (
	// SiteAnnouncementRead is a globally accessible object for table site_announcement_read operations.
	SiteAnnouncementRead = siteAnnouncementReadDao{internal.NewSiteAnnouncementReadDao()}
)

// Add your custom methods and functionality below.
