// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// siteMessageDao is the data access object for the table site_message.
// You can define custom methods on it to extend its functionality as needed.
type siteMessageDao struct {
	*internal.SiteMessageDao
}

var (
	// SiteMessage is a globally accessible object for table site_message operations.
	SiteMessage = siteMessageDao{internal.NewSiteMessageDao()}
)

// Add your custom methods and functionality below.
