// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// siteAuditDao is the data access object for the table site_audit.
// You can define custom methods on it to extend its functionality as needed.
type siteAuditDao struct {
	*internal.SiteAuditDao
}

var (
	// SiteAudit is a globally accessible object for table site_audit operations.
	SiteAudit = siteAuditDao{internal.NewSiteAuditDao()}
)

// Add your custom methods and functionality below.
