// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// sysCronLogDao is the data access object for the table sys_cron_log.
// You can define custom methods on it to extend its functionality as needed.
type sysCronLogDao struct {
	*internal.SysCronLogDao
}

var (
	// SysCronLog is a globally accessible object for table sys_cron_log operations.
	SysCronLog = sysCronLogDao{internal.NewSysCronLogDao()}
)

// Add your custom methods and functionality below.
