// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// trackerAgentWhitelistDao is the data access object for the table tracker_agent_whitelist.
// You can define custom methods on it to extend its functionality as needed.
type trackerAgentWhitelistDao struct {
	*internal.TrackerAgentWhitelistDao
}

var (
	// TrackerAgentWhitelist is a globally accessible object for table tracker_agent_whitelist operations.
	TrackerAgentWhitelist = trackerAgentWhitelistDao{internal.NewTrackerAgentWhitelistDao()}
)

// Add your custom methods and functionality below.
