// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// trackerSnatchDao is the data access object for the table tracker_snatch.
// You can define custom methods on it to extend its functionality as needed.
type trackerSnatchDao struct {
	*internal.TrackerSnatchDao
}

var (
	// TrackerSnatch is a globally accessible object for table tracker_snatch operations.
	TrackerSnatch = trackerSnatchDao{internal.NewTrackerSnatchDao()}
)

// Add your custom methods and functionality below.
