// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// trackerPeerDao is the data access object for the table tracker_peer.
// You can define custom methods on it to extend its functionality as needed.
type trackerPeerDao struct {
	*internal.TrackerPeerDao
}

var (
	// TrackerPeer is a globally accessible object for table tracker_peer operations.
	TrackerPeer = trackerPeerDao{internal.NewTrackerPeerDao()}
)

// Add your custom methods and functionality below.
