// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// trackerEventIdempotencyDao is the data access object for the table tracker_event_idempotency.
// You can define custom methods on it to extend its functionality as needed.
type trackerEventIdempotencyDao struct {
	*internal.TrackerEventIdempotencyDao
}

var (
	// TrackerEventIdempotency is a globally accessible object for table tracker_event_idempotency operations.
	TrackerEventIdempotency = trackerEventIdempotencyDao{internal.NewTrackerEventIdempotencyDao()}
)

// Add your custom methods and functionality below.
