// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package accounting

import (
	"server/api/accounting"
)

type ControllerV1 struct{}

func NewV1() accounting.IAccountingV1 {
	return &ControllerV1{}
}
