// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package site

import (
	"server/api/site"
)

type ControllerV1 struct{}

func NewV1() site.ISiteV1 {
	return &ControllerV1{}
}
